---
#
# Ansible managed
#
language: python

python:
  - "3.8"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="centos" tag="7"
    - image="opensuse" tag="latest"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack: "W+w07vaTIULFdRwTDVKtoD7q9PgusEuN3jDDhmBR8nPzrZhe1Trzk3KBo2ac5ImXW7YoSfzvGQv2RsOQuHAm3wUmFlvdKDG/bbs6K/DkUINE//rFFSMsTzKzIKHzaXvzQ+gTHP2jCFSeqsGpW7+EkS/a7J5cqrp9VpuZJ97PbsV3vLqwo/GVvYEpAdnVR9xV4SNtDMd6vN3dG0kF84jC8CJJLkMRcxvHHPMSUBmk9xsxXptkB/WjwRuutiIrW+ttARK6WrwWBaru5DXA2PDapdCT+P4F6/cq074jpi7QHWQopmmNrr1SuGeTNEGTNnll+kgtYHAea1JL9QGELyaBwTU1d5d3OZ91zfEOn7q4SULPaXHpvs20Ae4JlWCZ2DM8WWVnumgNuz/58cg/oaqYxvg88wJepdryxs9JqPftqyjcImFcCQNvFKmXWD7CW4/LO/L5F94QzCjPPS4fNtS1CtxUDF5MDL8sRatcbE8Oq2EwBkuqTqx+goKjgK4IsUeO8Glfppyal1EP4CG/CNDVOBdw8f5yhjBYusMZgtsl60P0HdkzlmShrvowmoVYsbAIMvFY4Q5R3hZRu8spoYiZQXY8b4/SGsb/cj4SD1s0qnvBVWRqUmxhFZ54tmuw70Sb+z7EO9w0tHGMuFQBBi6c4dBCNFKF6TPwlB8JsfsHVaM="
  email: false
