---
#
# Ansible managed
#
language: python

python:
  - "3.7"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="centos" tag="7"
    - image="opensuse" tag="latest"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: pEoxPPYMkXcKF52wmIOT2q2qrCGUK4aZSJsiDQyu1lQLpVTRyaE2+EU+1AzKvH1Zvh3QkSii+HAaMliw0glGDXZ5Q01vSdlWmnOWdJh+5OlKp9OpCCiI+tq6GKDjngLG0xX6uihxSkFqZZvUOSgRzpdQL3nJ6RAE3wifRlyL5rYwvHAUqgfhCWwbl6JhWrItkAvbap8pX37IbxX5f1vYTfvb6djBTnwd/vDfc77Bhz4NwUuoym+mJ68RC0VWmQw64//+itWuOdgCIrH+UCU7PuLSGNE5mJIxmW0DA23UZ50jXMqjkQfvB93wVNKMf+hEIUwFP1RzS5lXZ7tDy5RYbGPQQfKvFweaI3tbzBTBkL2HwEEhohj9X/YL0bqddMm8X8ukFKsbCWSIBtsdjwu4lyGp7rDNl9y2igoavdFAX8oE7ZfknFXlnn7soNiUAdGUMxjYTnu93pfGVh3NJYhnvTVKFjsMgXnTV+CgZeiBTvvNgOgZAeuoXCGW4kld99uub1BjdcRy7Dx2wAAvdtmaJxt0kv7gxXrCYNi+5oidqLy4g/EeOeYEPkYZbV6cPMQ5e12czzz8em4cfp5TjUa1RsKph/hLf4gqxjqZjsPn9jN84T8+/GBq9SQlaxR8VN2vP3dasiBXRQZy6FvfDOFkM9NoahuQFMmfX/HK215d1rs=
  email: false
